In [278]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import csv

In [330]:
# make path to files (awards)
csv_awards = "AwardsPlayers.csv"
csv_people = "People.csv"
csv_hof = "HallOfFame.csv"

# read file and make into dataframe
awards_df = pd.read_csv(csv_awards,
                             keep_default_na=False, na_values=[""])
hof_df = pd.read_csv(csv_hof,  
                             keep_default_na=False, na_values=[""])
#check data frames
#awards_data_df.head()
#hof_df

#create merged drata frame of hof and awards
merged_df = pd.merge(awards_df, hof_df, on='playerID', how="left")
#merged_df
merged = merged_df.loc[merged_df.category == "Player",("playerID","awardID", "yearID_x" , "inducted", "yearID_y", "category")]
#merged

#summary of players who got awards but not necessarily in hof
awardsummary = merged.sort_values(['inducted','category', 'playerID','yearID_y','awardID'])
awardsummary = pd.DataFrame(awardsummary)
awardsummary

,playerID,awardID,yearID_x,inducted,yearID_y,category
22182,abbotji01,Hutch Award,1995,N,2005.0,Player
21467,abbotji01,TSN All-Star,1991,N,2005.0,Player
350,adamsba01,Baseball Magazine All-Star,1909,N,1937.0,Player
434,adamsba01,Baseball Magazine All-Star,1909,N,1937.0,Player
351,adamsba01,Baseball Magazine All-Star,1909,N,1938.0,Player
435,adamsba01,Baseball Magazine All-Star,1909,N,1938.0,Player
352,adamsba01,Baseball Magazine All-Star,1909,N,1939.0,Player
436,adamsba01,Baseball Magazine All-Star,1909,N,1939.0,Player
353,adamsba01,Baseball Magazine All-Star,1909,N,1942.0,Player
437,adamsba01,Baseball Magazine All-Star,1909,N,1942.0,Player
354,adamsba01,Baseball Magazine All-Star,1909,N,1945.0,Player
438,adamsba01,Baseball Magazine All-Star,1909,N,1945.0,Player
355,adamsba01,Baseball Magazine All-Star,1909,N,1946.0,Player
439,adamsba01,Baseball Magazine All-Star,1909,N,1946.0,Player
356,adamsba01,Baseball Magazine All-Star,1909,N,1947.0,Player
440,adamsba01,Baseball Magazine All-Star,1909,N,1947.0,Player
357,adamsba01,Baseball Magazine All-Star,1909,N,1948.0,Player
441,adamsba01,Baseball Magazine All-Star,1909,N,1948.0,Player
358,adamsba01,Baseball Magazine All-Star,1909,N,1949.0,Player
442,adamsba01,Baseball Magazine All-Star,1909,N,1949.0,Player
359,adamsba01,Baseball Magazine All-Star,1909,N,1950.0,Player
443,adamsba01,Baseball Magazine All-Star,1909,N,1950.0,Player
360,adamsba01,Baseball Magazine All-Star,1909,N,1951.0,Player
444,adamsba01,Baseball Magazine All-Star,1909,N,1951.0,Player
361,adamsba01,Baseball Magazine All-Star,1909,N,1952.0,Player
445,adamsba01,Baseball Magazine All-Star,1909,N,1952.0,Player
362,adamsba01,Baseball Magazine All-Star,1909,N,1953.0,Player
446,adamsba01,Baseball Magazine All-Star,1909,N,1953.0,Player
363,adamsba01,Baseball Magazine All-Star,1909,N,1954.0,Player
447,adamsba01,Baseball Magazine All-Star,1909,N,1954.0,Player
...,...,...,...,...,...,...
16748,yastrca01,Gold Glove,1971,Y,1989.0,Player
17932,yastrca01,Gold Glove,1977,Y,1989.0,Player
16166,yastrca01,Hutch Award,1967,Y,1989.0,Player
16168,yastrca01,Most Valuable Player,1967,Y,1989.0,Player
15297,yastrca01,TSN All-Star,1963,Y,1989.0,Player
15790,yastrca01,TSN All-Star,1965,Y,1989.0,Player
16197,yastrca01,TSN All-Star,1967,Y,1989.0,Player
16261,yastrca01,TSN Major League Player of the Year,1967,Y,1989.0,Player
16265,yastrca01,TSN Player of the Year,1967,Y,1989.0,Player
16187,yastrca01,Triple Crown,1967,Y,1989.0,Player
76,youngcy01,Baseball Magazine All-Star,1908,Y,1937.0,Player
153,youngcy01,Baseball Magazine All-Star,1908,Y,1937.0,Player
27,youngcy01,Pitching Triple Crown,1901,Y,1937.0,Player
2271,youngro01,Baseball Magazine All-Star,1920,Y,1972.0,Player
2506,youngro01,Baseball Magazine All-Star,1921,Y,1972.0,Player
2741,youngro01,Baseball Magazine All-Star,1922,Y,1972.0,Player
2997,youngro01,Baseball Magazine All-Star,1923,Y,1972.0,Player
3322,youngro01,Baseball Magazine All-Star,1924,Y,1972.0,Player
19154,yountro01,Gold Glove,1982,Y,1999.0,Player
19205,yountro01,Most Valuable Player,1982,Y,1999.0,Player
21056,yountro01,Most Valuable Player,1989,Y,1999.0,Player
18714,yountro01,Silver Slugger,1980,Y,1999.0,Player
19247,yountro01,Silver Slugger,1982,Y,1999.0,Player
21088,yountro01,Silver Slugger,1989,Y,1999.0,Player
18299,yountro01,TSN All-Star,1978,Y,1999.0,Player
18763,yountro01,TSN All-Star,1980,Y,1999.0,Player
19302,yountro01,TSN All-Star,1982,Y,1999.0,Player
21125,yountro01,TSN All-Star,1989,Y,1999.0,Player
19346,yountro01,TSN Major League Player of the Year,1982,Y,1999.0,Player
19349,yountro01,TSN Player of the Year,1982,Y,1999.0,Player

In [331]:
#lets see how many awards per player using groupby....count()
awardsummary.groupby("awardID")["playerID"].count()

awardID
ALCS MVP                                 27
All-Star Game MVP                       173
Babe Ruth Award                         212
Baseball Magazine All-Star             9553
Branch Rickey Award                      23
Comeback Player of the Year               4
Cy Young Award                          197
Gold Glove                             2717
Hank Aaron Award                         30
Hutch Award                              81
Lou Gehrig Memorial Award               244
Most Valuable Player                    879
NLCS MVP                                 55
Pitching Triple Crown                   153
Roberto Clemente Award                  108
Rolaids Relief Man Award                155
Rookie of the Year                      218
Silver Slugger                         1122
TSN All-Star                           5294
TSN Fireman of the Year                 214
TSN Guide MVP                           265
TSN Major League Player of the Year     310
TSN Pitcher of the Year                 339
TSN Player of the Year                  516
TSN Reliever of the Year                  8
Triple Crown                             61
World Series MVP                        138
Name: playerID, dtype: int64

In [297]:
#list of all players that got awards INCLUDING ones who weren't inducted in the HOF and orgnize
awardsnohof = merged_df.loc[merged_df.category == "Player", ("playerID","awardID", "yearID_x" , "inducted", "yearID_y", "category")]

#awardsnohof.head()

#lets see how many awards per player using groupby....count()
awardsnohof.groupby("awardID")["playerID"].count()

awardID
ALCS MVP                                 27
All-Star Game MVP                       173
Babe Ruth Award                         212
Baseball Magazine All-Star             9553
Branch Rickey Award                      23
Comeback Player of the Year               4
Cy Young Award                          197
Gold Glove                             2717
Hank Aaron Award                         30
Hutch Award                              81
Lou Gehrig Memorial Award               244
Most Valuable Player                    879
NLCS MVP                                 55
Pitching Triple Crown                   153
Roberto Clemente Award                  108
Rolaids Relief Man Award                155
Rookie of the Year                      218
Silver Slugger                         1122
TSN All-Star                           5294
TSN Fireman of the Year                 214
TSN Guide MVP                           265
TSN Major League Player of the Year     310
TSN Pitcher of the Year                 339
TSN Player of the Year                  516
TSN Reliever of the Year                  8
Triple Crown                             61
World Series MVP                        138
Name: playerID, dtype: int64

In [298]:
awardsnohof = awardsnohof.loc[awardsnohof.inducted == "Y", ("playerID", "awardID", "yearID_x", "inducted", "yearID_y", "category")]
awardsnohof.head()

,playerID,awardID,yearID_x,inducted,yearID_y,category
14432,aaronha01,Gold Glove,1958.0,Y,1982.0,Player
14434,aaronha01,Gold Glove,1959.0,Y,1982.0,Player
14436,aaronha01,Gold Glove,1960.0,Y,1982.0,Player
14442,aaronha01,Lou Gehrig Memorial Award,1970.0,Y,1982.0,Player
14431,aaronha01,Most Valuable Player,1957.0,Y,1982.0,Player

In [257]:
# how many total number of players got award(s)
# find unique players by using .unique()
players = len(awardsnohof['playerID'].unique())
awards = len(awardsnohof['awardID'].unique())

print("The number of total players is " + str(players)+ ".")
print("The number of different awards is " + str(awards)+ ".")

The number of total players is 256.
The number of different awards is 27.