In [103]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import csv

In [104]:
# make path to files (awards)
csv_awards = "AwardsPlayers.csv"
csv_people = "People.csv"
csv_hof = "HallOfFame.csv"

# read file and make into dataframe
awards_df = pd.read_csv(csv_awards,
                             keep_default_na=False, na_values=[""])
hof_df = pd.read_csv(csv_hof,  
                             keep_default_na=False, na_values=[""])
#check data frames
#awards_data_df.head()
#hof_df

#create merged drata frame of hof and awards
merged_df = pd.merge(awards_df, hof_df, on='playerID', how="left")
#rename column titles
merged_df.rename(columns={"yearID_x":"award_year", "yearID_y":"year_inducted"}, inplace=True)

#show only row values under category column to show "player" 
results = merged_df.loc[merged_df.category == "Player",("playerID","awardID", "award_year" , "inducted", "year_inducted", "category")]
#results

#sort to see summary of players who got awards but not necessarily in hof
awardsummary = results.sort_values(['inducted','category', 'playerID','award_year','awardID'])
awardsummary = pd.DataFrame(awardsummary)
awardsummary.head()

,playerID,awardID,award_year,inducted,year_inducted,category
21467,abbotji01,TSN All-Star,1991,N,2005.0,Player
22182,abbotji01,Hutch Award,1995,N,2005.0,Player
350,adamsba01,Baseball Magazine All-Star,1909,N,1937.0,Player
351,adamsba01,Baseball Magazine All-Star,1909,N,1938.0,Player
352,adamsba01,Baseball Magazine All-Star,1909,N,1939.0,Player

In [115]:
#lets see how many how many players got which awards INCLUDING both inducted and not inducted using groupby....count()
groupby1 = awardsummary.groupby("awardID")["playerID"].count()
allplayers = groupby1.to_frame()
allplayers 

#see how many different awards there are all players including ones that
#awards = len(awardsummary['awardID'].unique())
#awards "27 different awards"

                                     playerID
awardID
ALCS MVP                                   27
All-Star Game MVP                         173
Babe Ruth Award                           212
Baseball Magazine All-Star               9553
Branch Rickey Award                        23
Comeback Player of the Year                 4
Cy Young Award                            197
Gold Glove                               2717
Hank Aaron Award                           30
Hutch Award                                81
Lou Gehrig Memorial Award                 244
Most Valuable Player                      879
NLCS MVP                                   55
Pitching Triple Crown                     153
Roberto Clemente Award                    108
Rolaids Relief Man Award                  155
Rookie of the Year                        218
Silver Slugger                           1122
TSN All-Star                             5294
TSN Fireman of the Year                   214
TSN Guide MVP                             265
TSN Major League Player of the Year       310
TSN Pitcher of the Year                   339
TSN Player of the Year                    516
TSN Reliever of the Year                    8
Triple Crown                               61
World Series MVP                          138

In [114]:
#list of only inducted HOF players that got awards and orgnize
hofawards0 = results.loc[merged_df.inducted == "Y", ("playerID","awardID", "award_year" , "inducted", "year_inducted", "category")]
#awardsandhof.head()

#lets see how many awards per player using groupby....count()
hofawards0.groupby("awardID")["playerID"].count()

#convert to dataframe
groupby2 = hofawards0.groupby("awardID")["playerID"].count()
hofawards = groupby2.to_frame()
hofawards 

#see how many different awards there are for people who are in the HOF
#awards1 = len(hofawards0['awardID'].unique())
#awards1 "26 different awards"

                                     playerID
awardID
ALCS MVP                                    5
All-Star Game MVP                          20
Babe Ruth Award                            21
Baseball Magazine All-Star                861
Branch Rickey Award                         8
Comeback Player of the Year                 1
Cy Young Award                             41
Gold Glove                                257
Hutch Award                                13
Lou Gehrig Memorial Award                  26
Most Valuable Player                      100
NLCS MVP                                    4
Pitching Triple Crown                      27
Roberto Clemente Award                     17
Rolaids Relief Man Award                   14
Rookie of the Year                         16
Silver Slugger                            151
TSN All-Star                              576
TSN Fireman of the Year                    15
TSN Guide MVP                              25
TSN Major League Player of the Year        41
TSN Pitcher of the Year                    48
TSN Player of the Year                     48
TSN Reliever of the Year                    2
Triple Crown                               14
World Series MVP                           19

In [124]:
final = pd.merge(allplayers, hofawards, on='awardID', how="left")
final = final.rename(columns={"playerID_x":"all_players", "playerID_y":"HOF"},)
final

                                     all_players    HOF
awardID
ALCS MVP                                      27    5.0
All-Star Game MVP                            173   20.0
Babe Ruth Award                              212   21.0
Baseball Magazine All-Star                  9553  861.0
Branch Rickey Award                           23    8.0
Comeback Player of the Year                    4    1.0
Cy Young Award                               197   41.0
Gold Glove                                  2717  257.0
Hank Aaron Award                              30    NaN
Hutch Award                                   81   13.0
Lou Gehrig Memorial Award                    244   26.0
Most Valuable Player                         879  100.0
NLCS MVP                                      55    4.0
Pitching Triple Crown                        153   27.0
Roberto Clemente Award                       108   17.0
Rolaids Relief Man Award                     155   14.0
Rookie of the Year                           218   16.0
Silver Slugger                              1122  151.0
TSN All-Star                                5294  576.0
TSN Fireman of the Year                      214   15.0
TSN Guide MVP                                265   25.0
TSN Major League Player of the Year          310   41.0
TSN Pitcher of the Year                      339   48.0
TSN Player of the Year                       516   48.0
TSN Reliever of the Year                       8    2.0
Triple Crown                                  61   14.0
World Series MVP                             138   19.0

The number of total players is 256.
The number of different awards is 27.